FROM node:18-alpine AS build

RUN adduser -D app

USER app
WORKDIR /app

COPY --chown=app:app package*.json ./
RUN npm install

COPY --chown=app:app . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
